### ISSUE TITLE
  Add changelog

### ISSUE THREAD

**Issue by johnjohndoe** [klinker24/Android-TextView-LinkBuilder#10]
Please consider providing a textual **changelog** so it is easier for users to see what changes from version to version.

* [Example changelog of devise](https://github.com/plataformatec/devise/blob/v3.1.1/CHANGELOG.md)
* [Example changelog of cancan](https://github.com/ryanb/cancan/blob/1.6.10/CHANGELOG.rdoc)
* [Example changelog of angular.js](https://github.com/angular/angular.js/blob/v1.1.5/CHANGELOG.md)
* [GitHub offers release notes](https://github.com/jeffkreeftmeijer/fuubar/releases/new)
* [GitHub release notes example of better_errors](https://github.com/charliesome/better_errors/releases)
* [Umweltzone](https://github.com/johnjohndoe/Umweltzone/blob/master/CHANGELOG.md)

**Comment by klinker24** [comment]
Done and done. Thanks

**Comment by johnjohndoe** [comment]
Nice. Thank you.
