### ISSUE TITLE
minSdk 14?

### ISSUE THREAD

**Issue by BoD** [klinker24/Android-TextView-LinkBuilder#11]
Are features from sdk 14 actually used by the code?
If not, you might consider lowering it, to make this library usable by apps targeting < 14.

**Comment by klinker24** [comment]
Sure thing. Don't really even consider people still use less than that I guess.

https://github.com/klinker24/Android-TextView-LinkBuilder/commit/f9c58f94219ff1b3dd1535f8a1c55524064f6a9e

**Comment by BoD** [comment]
Thanks :-) 
Yeah apps targeting dinosaur devices still exist ;-)
