### ISSUE TITLE
Customizable default color

### ISSUE THREAD

**Issue by johnjohndoe** [klinker24/Android-TextView-LinkBuilder#14]
It would be nice if users could set their own default text color. In many cases applications use the same color for all the links. If the default color has been set there is no need to repeatedly call `Link#setTextColor()` then.
Setting the default color could be implemented through resource attributes I suppose.

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <declare-styleable name="Theme">
        <attr name="text_link_default_color" format="color" />
    </declare-styleable>
</resources>
```

**Comment by klinker24** [comment]
Done, thanks for the suggestion, had never done anything quite like this before

https://github.com/klinker24/Android-TextView-LinkBuilder/commit/e45c06e3dc8fdcf6b831d675d3879197823706e3

**Comment by johnjohndoe** [comment]
Nice. I will check it out.
