### ISSUE TITLE
Conform to semantic versioning

### ISSUE THREAD

**Issue by johnjohndoe** [klinker24/Android-TextView-LinkBuilder#17]
Please considering changing your versioning scheme to stick to [semantic versioning](http://semver.org/). The current version number increase does not conform to this convention as far as I can jugde. I refer to adding new features such as [setting the default color](https://github.com/klinker24/Android-TextView-LinkBuilder/issues/14) which should cause an increase of the minor version number.

**Comment by klinker24** [comment]
Noted for the future. I did not consider that feature to be something worth a minor release, so I chose to keep it in the 1.0 release.

**Comment by johnjohndoe** [comment]
The new feature would be a version change from `v.1.0.z` to `v.1.1.0`.
