### ISSUE TITLE
Support for Links

### ISSUE THREAD

**Issue by juzer10** [klinker24/Android-TextView-LinkBuilder#18]
This is a very useful library but is there anyway that you could add support for clicking web addresses? The default implementation for TextView in the Android SDK doesn't play well with ListViews. 

If you happen to use a certain regex, it would be great if you could share it.

**Comment by klinker24** [comment]
For Talon, I use the VALID_URL pattern on this page. I will add this to the readme for anyone else who wonders. This is part of google's regular expressions page from AOSP

https://github.com/klinker24/Talon-for-Twitter/blob/master/src/main/java/com/klinker/android/twitter/utils/text/Regex.java
