### ISSUE TITLE
How to apply to different portion of text

### ISSUE THREAD

**Issue by shollynoob** [klinker24/Android-TextView-LinkBuilder#44]
Hello , please how can i  apply this to different portion of text eg I want **to** apply  this, **that** and **this**

i don't know if you understand what i mean, i want to apply to series of text

**Comment by klinker24** [comment]
You just need to build links for the text that you want to "linkify". For example, if you wanted to add a click action to the text "click here" in the following sentence:

````
Please click here to view our terms of service.
```

You would create a link, as described in the sample app:

```java
Link link = new Link("click here")
    .setOnClickListener(new Link.OnClickListener() {
        @Override
        public void onClick(String clickedText) {

        }
    });

LinkBuilder.on(textView)
    .addLink(link)
    .build();
```

**Comment by shollynoob** [comment]
yes i was able to apply to one text, if i want to apply "click", "view", "terms" and "service" in your example above, can i pass a parameters or an "if" statement to the build link?

**Comment by klinker24** [comment]
I don't really understand your question, sorry... Maybe an example use-case would be good. 

You could apply more than one link onto `LinkBuilder`:

```java
LinkBuilder.on(textView)
    .addLink(link1)
    .addLink(link2)
    .addLink(link3)
    .build()
```

**Comment by shollynoob** [comment]
i so much appreciate your response, and really new to programming sought off though.
let take for instance i have this statement   **The quick brown fox jumps over the lazy dog** , and i want to add OnClickListener to "quick", "fox", "jump" and "dog" to handle different event.

See what i have below

   Link a = new Link("quick");
        Link b = new Link("fox");
        Link c = new Link("jump");
        Link d = new Link("dog")
                .setTextColor(Color.parseColor("#259B24"))                 
                .setTextColorOfHighlightedLink(Color.parseColor("#0D3D0C")) 
                .setHighlightAlpha(.4f)                                     
                .setUnderlined(false)                                       
                .setBold(true)                                              
                .setOnClickListener(new Link.OnClickListener() {
                    @Override
                    public void onClick(String clickedText) {
     
                    }
                });
        TextView note = (TextView) findViewById(R.id.note );
        LinkBuilder.on(note)
                .addLink(a)
                .addLink(b)
                .addLink(c)
                .addLink(d)
                .build(); 

How to get the click event for a, b, c, d is my issue

**Comment by klinker24** [comment]
Well, you are setting up a click event for d already. You can do the same thing for a, b, and c:

```java
Link a = new Link("quick")
    .setOnClickListener(new Link.OnClickListener() {
        @Override
        public void onClick(String clickedText) {

        }
    });
Link b = new Link("fox")
    .setOnClickListener(new Link.OnClickListener() {
        @Override
        public void onClick(String clickedText) {

        }
    });
Link c = new Link("jump")
    .setOnClickListener(new Link.OnClickListener() {
        @Override
        public void onClick(String clickedText) {

        }
    });
Link d = new Link("dog")
    .setOnClickListener(new Link.OnClickListener() {
        @Override
        public void onClick(String clickedText) {

        }
    });

TextView note = (TextView) findViewById(R.id.note);
LinkBuilder.on(note)
    .addLink(a)
    .addLink(b)
    .addLink(c)
    .addLink(d)
    .build(); 
```

**Comment by shollynoob** [comment]
Thanks
