### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by cnsilvan** [klinker24/Android-TextView-LinkBuilder#46]
java.lang.NullPointerException: 
Attempt to invoke virtual method 'int java.lang.String.indexOf(java.lang.String, int)' on a null object reference 
at java.util.regex.Pattern.quote(Pattern.java:439) 
at com.klinker.android.link_builder.LinkBuilder.on(Unknown Source) 
                                                setText
                                                setContext
                                                addLinks
                                                build
                                                addLinkToSpan
                                                addLinkToSpan
                                                applyLink

**Comment by cnsilvan** [comment]
private void addLinkToSpan(Spannable s, Link link) {
        // get the current text
        **maybe this line** 
        Pattern pattern = Pattern.compile(Pattern.quote(link.getText()));
        **maybe this line** 
        Matcher matcher = pattern.matcher(text);

        // find one or more links inside the text
        while (matcher.find()) {

            // find the start and end point of the linked text within the TextView
            int start = matcher.start();

            //int start = text.indexOf(link.getText());
            if (start >= 0) {
                int end = start + link.getText().length();

                // add link to the spannable text
                applyLink(link, new Range(start, end), s);
            }

            // if we are only looking for the first occurrence of this pattern,
            // then quit now and don't look any further
            if (findOnlyFirstMatch) {
                break;
            }
        }
    }

**Comment by klinker24** [comment]
For this, it would be very helpful if you could provide an example that will throw the exception.

**Comment by klinker24** [comment]
Closing for no followup or method to reproduce it
