### ISSUE TITLE
Request: prepend links

### ISSUE THREAD

**Issue by SanderTuit** [klinker24/Android-TextView-LinkBuilder#5]
Thanks for making this library public, it's very useful. I have a feature request: it would be nice to be able to prepend some text to a link. For instance: I'm using two different link colors for internal and external links, but I'd like to add a character to indicate it's an external link. Perhaps something like:

link.setPrependedText('text here')

**Comment by klinker24** [comment]
Done. Thanks for the suggestion. Sorry it took awhile, been busy lately!

https://github.com/klinker24/Android-TextView-LinkBuilder/commit/05e066c972e0df0e43f6a6ce87ed591fc6d67d73
