### ISSUE TITLE
How to get the position of text clicked?

### ISSUE THREAD

**Issue by faizan48** [klinker24/Android-TextView-LinkBuilder#59]
I want to change the text on that specific clicked area.

**Comment by klinker24** [comment]
To do this, you would have to subclass the [`TouchableMovementMethod`](https://github.com/klinker24/Android-TextView-LinkBuilder/blob/master/library/src/main/java/com/klinker/android/link_builder/TouchableMovementMethod.kt). This isn't something that is planned to be built into the library, but it would be possible to create this sort of thing. With the movement method, you can know what text was clicked.
