### ISSUE TITLE
There is 2 major issues and 1 Imporvment

### ISSUE THREAD

**Issue by moali2402** [klinker24/Android-TextView-LinkBuilder#6]
1st Issue : 
setHighlightAlpha Doesn't work with Patterns.
The Fix : You missed     this.highlightAlpha = link.getHighlightAlpha(); in the Link(Link link) constructor.

2nd Issue: If TextView doesn't have any links that match patterns, it doesn't show any text in the textView.
The Fix: Move  this.spannable = SpannableString.valueOf(text);  from addLinkToSpan to any method before Build. or to be more precise, any where before turnPatternsToLinks(); method is called in build.

Improvements : Support LinkBuilder Class using String as parameter not TextView.

**Comment by klinker24** [comment]
2 was fixed this morning and your improvement is being discussed here:

https://github.com/klinker24/Android-TextView-LinkBuilder/issues/3

**Comment by klinker24** [comment]
The first one is now fixed: https://github.com/klinker24/Android-TextView-LinkBuilder/commit/73110639f9060fd27df3b880d9d47f0dde41c9ee
