### ISSUE TITLE
Links last word Clickable in any area after the last word

### ISSUE THREAD

**Issue by moali2402** [klinker24/Android-TextView-LinkBuilder#7]
There seems to be an issue if i have the link as the last word in the TextView and TextView fills parent and there is a massive space after the last word, if i click on the emtpy space after the last word. The last link gets clicked.

**Comment by klinker24** [comment]
This has actually been an issue with my app Talon as well, from the start. To be honest, I have no idea how to solve this or where to start even.

Any help on this issue is greatly appreciated.

**Comment by klinker24** [comment]
Closed with https://github.com/klinker24/Android-TextView-LinkBuilder/commit/e815450cc13620eef497bd1025bdd7b961707b82

**Comment by answer1989** [comment]
this solution will another problem, when the text is @xx, it cannot be click, because of the below code,
`if (off != end && off != end - 1)` ,  when I debug the code, i can see  `off == end - 1` in my situation,so it jump out ,and cannot click.

**Comment by siyanew** [comment]
I have this problem on Huawei Phones ... whats wrong with them ?
